version: '3.8'
services:
  careerpath:
    build: 
      context: ./backend/careerPath
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - careerpath

