version: '3.8'
services:
  careerpath:
    build:
      context: ./backend/careerPath
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    env_file:
      - ./backend/careerPath/.env
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - careerpath
