global:
  scrape_interval: 15s  # Set the interval at which Prometheus scrapes metrics

scrape_configs:
  - job_name: 'nodejs-backend'
    static_configs:
      - targets: ['careerpath:3003']  # Point to your Node.js application for metrics

  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb_exporter:9216']  # Point to the MongoDB exporter for metrics
